WITH DD AS (
SELECT DISTINCT DATEPART(YY,DT) YR, DATEPART(MM,DT) MN
FROM(
SELECT DATEADD(DAY,number+1,CAST(GETDATE() AS DATE)) DT
FROM master..spt_values
WHERE type = 'P'
AND DATEADD(DAY,number+1,GETDATE()) < GETDATE()+31*6
) A
), FCST AS (

SELECT ARPR.ARTNR , SUM(PROGNOSANTALPERIOD) FORECAST
FROM arpr
JOIN AR ON AR.ARTNR = ARPR.ARTNR AND AR.ForetagKod = ARPR.ForetagKod
JOIN DD ON LEFT(PROGNOSPERIOD,4) = YR  AND RIGHT(PROGNOSPERIOD,2) = MN
WHERE --ARPR.ARTNR = '2010' AND
ARPR.PrognosNiva = 3
AND AR.ItemStatusCode IN (0,1,8)
GROUP BY  ARPR.ARTNR

)

SELECT *
FROM (
SELECT
       ARS.ARTNR ITEM_ID,
       ARTBESKR ITEM_DESC,
       XITS.ITEMSTATUSDESCR ITEM_STATUS,
       CASE
              WHEN LEFT(ARS.ARTNR,1) = '4' THEN 'KIT'
              WHEN RIGHT(ARS.ARTNR,1) = '7' THEN 'TRIAL'
              WHEN RIGHT(ARS.ARTNR,1) = '9' THEN 'SAMPLE'
              ELSE 'FULL SIZE'
       END ITEM_TYPE,
       VG.VARUGRUPPBESKR ITEM_GROUP,
       ArtProdKlBESKR ITEM_CLASS_DESC,
       ARTKATBESKR ITEM_CAT_DESC,
       MIN(ISNULL(INKHANDL,'ZZ')) ITEM_BUYER,
       SUM(LAGSALDO) ON_HAND,
       SUM(LAGBESTANT) ON_ORDER,
       SUM(FORECAST) FORECAST,
       SUM((LAGSALDO +LAGBESTANT )-FORECAST) OVERSTOCK
       FROM ARS WITH (NOLOCK)
       JOIN AR ON AR.FORETAGKOD = ARS.FORETAGKOD AND AR.ARTNR = ARS.ARTNR
       JOIN XITS ON XITS.FORETAGKOD = AR.FORETAGKOD AND XITS.ITEMSTATUSCODE = AR.ITEMSTATUSCODE
       JOIN VG ON VG.FORETAGKOD = AR.FORETAGKOD AND VG.VARUGRUPPKOD = AR.VARUGRUPPKOD
       JOIN xakh ON xakh.FORETAGKOD = AR.FORETAGKOD AND xakh.ArtKat = AR.ArtKat
       JOIN xp ON  xp.FORETAGKOD = AR.FORETAGKOD AND xp.ArtProdKlass = AR.ArtProdKlass
       LEFT OUTER JOIN FCST ON  ARS.ARTNR = FCST.ARTNR
       WHERE ARS.FORETAGKOD = 0
       --AND XITS.ItemStatusCode in (0,1)
       AND ARS.LAGSTALLE IN (0,394)
       and RIGHT(ARS.ARTNR,1) != 'R'
       AND AR.ItemStatusCode IN (0,1,8)

GROUP BY
       ARS.ARTNR ,
       ARTBESKR ,
       XITS.ITEMSTATUSDESCR ,
       CASE
              WHEN LEFT(ARS.ARTNR,1) = '4' THEN 'KIT'
              WHEN RIGHT(ARS.ARTNR,1) = '7' THEN 'TRIAL'
              WHEN RIGHT(ARS.ARTNR,1) = '9' THEN 'SAMPLE'
              ELSE 'FULL SIZE'
       END ,
       VG.VARUGRUPPBESKR ,
       ArtProdKlBESKR ,
       ARTKATBESKR
) A
WHERE
OVERSTOCK > 0
AND NOT( ITEM_STATUS = 'To be discontinued' AND ON_HAND < 25)
